#!/usr/bin/env python3
"""Generate the per-architecture configuration document, in Markdown and Confluence markup.

    ./scripts/build-architectures.py

Writes docs/ARCHITECTURES.md and docs/confluence/ARCHITECTURES.confluence from the planner.
Every core list, kernel argument and diagram in both files is rendered from the same
plan.json the installer uses, so a document with a stale CPU list in it is not possible.

The diagrams are plain text. They have to fit a Confluence page, they have to survive a
copy-paste, and they have to be regenerated whenever the policy moves - none of which an
exported SVG does well.
"""
import argparse, datetime, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import textdiag
from docwriter import Confluence, Markdown
from docgen_common import CPU_NAME, ORDER, REPO, load_lltune

lltune = load_lltune()

INTRO = (
    "One layered diagram per supported metal shape, each carrying that shape's real core "
    "allocation and the actual values every layer installs: the kernel arguments, the "
    "cgroup cpusets, the runtime pinning targets and the core contract handed to the "
    "application.")

READING = (
    "Read each diagram downward. Layer 4 is what the application sees; layer 0 is the "
    "machine underneath. The constraint drawn between layers 2 and 1 is the only hard one "
    "in the design - a pulsar.slice that disagreed with isolcpus would keep serving "
    "traffic while its tail latency doubled, and nothing at run time would say so.")

NIC_INTRO = (
    "Exclusive cores are not interchangeable. The primary ENA adapter hangs off one PCIe "
    "root complex, which belongs to one NUMA node, and every packet descriptor and DMA "
    "buffer touched from another node pays a die crossing or a socket hop. Core isolation "
    "does not buy that back. So the planner ranks every node by its distance from the NIC "
    "and hands the application the exclusive cores in that order: tier 0 first.")

NIC_CAVEAT = (
    "AWS publishes no PCIe root-complex map, so which node the primary NIC sits on is an "
    "inference on every multi-node shape until a real host has been read. Run "
    "'lltune nic --live' on first contact with a shape and correct the profile. "
    "'lltune validate' fails if the installed plan's NIC node disagrees with the host, "
    "because a wrong NIC node turns the whole ranking upside down.")


# ---------------------------------------------------------------- data

def plans():
    policy = lltune.load_policy()
    for name in ORDER:
        prof = lltune.load_profile(name)
        plan = lltune.build_plan(lltune.topology_from_profile(prof), policy, name)
        yield name, prof, plan


def numa_mode(prof):
    return prof.get("numa_mode", "").split(" - ")[0]


def topo_line(prof, plan):
    t = plan["topology"]
    return (f"{prof['metal_sku']} - {CPU_NAME.get(prof['name'], '')} - "
            f"{t['sockets']} socket{'s' if t['sockets'] > 1 else ''} x "
            f"{t['total_cores'] // t['sockets']} cores - "
            f"{t['total_cpus']} vCPU to {t['total_cores']} usable - "
            f"{t['numa_nodes']} NUMA node{'s' if t['numa_nodes'] > 1 else ''} "
            f"({numa_mode(prof)}) - L3 domain {t['cores_per_l3']} cores")


def nic_status(prof, plan):
    """One line on how far the NIC node can be trusted for this shape."""
    if plan["topology"]["numa_nodes"] == 1:
        return "certain", "single NUMA node - the NIC is local to it whatever it hangs off"
    conf = prof.get("confidence", {}).get("nic_numa_node", "")
    return "inferred", conf.split(". ", 1)[-1].replace("Settle it with 'lltune nic --live'.",
                                                       "").strip() or conf


def caveats(prof):
    """Fields this profile records as inferred. nic_numa_node has its own section above."""
    out = []
    for k, v in prof.get("confidence", {}).items():
        if k == "nic_numa_node":
            continue
        if "ASSUMED" in v.upper():
            out.append(f"{k} - {v}")
    return out


# ---------------------------------------------------------------- document

def build(doc):
    rows = list(plans())
    today = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")

    doc.h(1, "Proposed configuration, by architecture")
    doc.panel("info",
              f"Generated by scripts/build-architectures.py on {today}. Do not hand-edit: "
              f"every core list, kernel argument and diagram below is rendered from the "
              f"planner, so it is what scripts/install.sh would actually write for that "
              f"shape. Regenerate after any change to profiles/policy.json or a profile.")
    doc.para(INTRO)
    doc.toc()

    doc.h(2, "How to read a diagram")
    doc.para(READING)
    doc.para("The four layers, and what each one is:")
    doc.table(
        ["Layer", "Mechanism", "When it takes effect"],
        [["4 - application core contract", "the two core lists the app pins its own threads to",
          "start-up; no reboot"],
         ["3 - runtime pinning", "IRQ affinity, ENA queue count, XPS, workqueues, governor",
          "every boot"],
         ["2 - cgroup v2 slices", "AllowedCPUs on the managed slices", "daemon-reload; immediate"],
         ["1 - boot isolation", "isolcpus, nohz_full, rcu_nocbs, irqaffinity",
          "requires a reboot"],
         ["0 - machine", "the cores the shape actually has", "-"]])

    # ------------------------------------------------------------ at a glance
    doc.h(2, "All seven at a glance")
    doc.table(
        ["Architecture", "Metal SKU", "CPU", "Cores", "NUMA", "hk", "irq", "shared",
         "exclusive", "NIC-local exclusive"],
        [[doc.mono(name), doc.mono(prof["metal_sku"]), CPU_NAME.get(name, ""),
          plan["topology"]["total_cores"], plan["topology"]["numa_nodes"],
          plan["roles"]["housekeeping"]["cpu_count"], plan["roles"]["irqnet"]["cpu_count"],
          plan["roles"]["shared"]["cpu_count"], plan["roles"]["exclusive"]["cpu_count"],
          plan["app"]["nic_local_exclusive_core_count"]]
         for name, prof, plan in rows])
    doc.para(
        "Policy: shared_ratio=0.15, min_exclusive_ratio=0.55, l3_align=true, cstate_max=1. "
        "Housekeeping and IRQ cores are reserved per NUMA node, which is why node count "
        "and not core count drives the platform's overhead. The last column is the part "
        "of the exclusive pool that is local to the primary NIC - on c8i-96xl that is 23 "
        "of 138 cores, and it is the number that actually bounds the latency-critical "
        "shard.")

    # ------------------------------------------------------------ nic locality
    doc.h(2, "NIC locality: which NUMA node is closest to the primary NIC")
    doc.para(NIC_INTRO)
    doc.para(
        "The ranking is computed, not configured. On a live host it comes from the ACPI "
        "SLIT plus the adapter's own numa_node. From a profile there is no SLIT to read, "
        "so it falls back to the structural model - the NIC's own node, then the rest of "
        "that socket, then the other socket.")
    doc.table(
        ["Architecture", "NUMA nodes", "NIC node", "Status", "NIC-local exclusive",
         "Node order, nearest first"],
        [[doc.mono(name), plan["topology"]["numa_nodes"],
          f"node{plan['nic_locality']['nic_numa_node']}",
          nic_status(prof, plan)[0],
          f"{plan['app']['nic_local_exclusive_core_count']} of "
          f"{plan['roles']['exclusive']['cpu_count']}",
          " > ".join(f"node{n}" for n in plan["nic_locality"]["node_order"])]
         for name, prof, plan in rows])
    doc.para("Why each shape has the status it has:")
    doc.bullets([f"{doc.mono(name)}: {nic_status(prof, plan)[1]}"
                 for name, prof, plan in rows])
    doc.panel("warning", NIC_CAVEAT, "The NIC node is inferred on every multi-node shape")
    doc.para("How to settle it on a real host of the shape:")
    doc.code("lltune nic --live        # adapter, its NUMA node, the SLIT, and the ranking\n"
             "lltune validate          # fails if the installed plan assumed the wrong node",
             language="bash")
    doc.para(
        "If the adapter reports numa_node = -1 the firmware exposed no _PXM for it. That is "
        "not a shape without NIC locality; it is a shape whose locality you cannot read, and "
        "the plan falls back to node 0. Treat the ranking as unproven and measure it instead "
        "- pin a load generator to one node at a time and compare.")

    # ------------------------------------------------------------ per shape
    for name, prof, plan in rows:
        doc.anchor(name)
        doc.h(2, name)
        doc.para(topo_line(prof, plan))

        doc.diagram(textdiag.layer_stack(plan, prof["metal_sku"], CPU_NAME.get(name, ""),
                                         numa_mode(prof)),
                    title=f"{name} - the four configuration layers")
        doc.diagram(textdiag.core_map(plan),
                    title=f"{name} - core map, NUMA nodes ordered by distance from the NIC")

        doc.table(
            ["Role", "CPUs", "Count", "Where it lives"],
            [["housekeeping", doc.mono(plan["roles"]["housekeeping"]["cpus"]),
              plan["roles"]["housekeeping"]["cpu_count"],
              "system.slice, user.slice, machine.slice, init.scope"],
             ["irqnet", doc.mono(plan["roles"]["irqnet"]["cpus"]),
              plan["roles"]["irqnet"]["cpu_count"], "irqnet.slice"],
             ["shared", doc.mono(plan["roles"]["shared"]["cpus"]),
              plan["roles"]["shared"]["cpu_count"],
              "no cpuset - the app pins its own threads here"],
             ["exclusive", doc.mono(plan["roles"]["exclusive"]["cpus"]),
              plan["roles"]["exclusive"]["cpu_count"], "pulsar.slice - isolated"]])

        doc.para("Per NUMA node, nearest the NIC first:")
        by_node = {n["node"]: n for n in plan["nodes"]}
        tier_label = {t["tier"]: t["label"] for t in plan["nic_locality"]["tiers"]}
        doc.table(
            ["Node", "NIC tier", "Cores", "housekeeping", "irq", "shared", "exclusive"],
            [[f"node{n}", f"{by_node[n]['nic_tier']} - {tier_label[by_node[n]['nic_tier']]}",
              by_node[n]["cores_total"],
              doc.mono(by_node[n]["housekeeping"]["cpus"]),
              doc.mono(by_node[n]["irqnet"]["cpus"]),
              doc.mono(by_node[n]["shared"]["cpus"]),
              doc.mono(by_node[n]["exclusive"]["cpus"])]
             for n in plan["nic_locality"]["node_order"]])

        app = plan["app"]
        doc.para("What the application is handed, in the order it should spend it:")
        doc.table(
            ["NIC tier", "Nodes", "Exclusive cores", "Count", "Shared cores"],
            [[t["tier"], ", ".join(f"node{n}" for n in t["nodes"]),
              doc.mono(app["exclusive_cores_by_tier"][str(t["tier"])]),
              len(lltune.expand(app["exclusive_cores_by_tier"][str(t["tier"])])),
              doc.mono(app["shared_cores_by_tier"][str(t["tier"])])]
             for t in plan["nic_locality"]["tiers"]])

        doc.expand("Full kernel command line",
                   doc.raw_code("\n".join(plan["cmdline"].split())))

        cav = caveats(prof)
        if cav:
            doc.panel("note", "\n".join(cav),
                      "Unverified for this shape - confirm with lltune topology --live")

    doc.h(2, "Where the rest of it is")
    doc.para(
        "The verbatim contents of every file these layers install are in CONFIG-REFERENCE. "
        "On a host, scripts/apply.sh plans from the real topology and shows the diff for all "
        "four layers before anything is written.")
    return doc.text()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--md", default=str(REPO / "docs" / "ARCHITECTURES.md"))
    ap.add_argument("--confluence",
                    default=str(REPO / "docs" / "confluence" / "ARCHITECTURES.confluence"))
    args = ap.parse_args()

    for path, cls in ((args.md, Markdown), (args.confluence, Confluence)):
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        text = build(cls())
        p.write_text(text)
        widest = max(len(x) for x in text.splitlines())
        print(f"wrote {p}  ({len(text.splitlines())} lines, widest {widest} cols)")


if __name__ == "__main__":
    main()
