#!/usr/bin/env python3
"""Generate docs/CONFIG-REFERENCE.md: the boot isolation and cgroup layers, every shape.

The document is rendered from the planner, exactly like the files install.sh writes to
disk. Hand-maintaining CPU lists in a document is the same failure mode the planner
exists to prevent, one level up: the doc drifts, someone trusts it, and the box they
build from it is subtly wrong.

    ./scripts/build-config-reference.py [-o docs/CONFIG-REFERENCE.md]
"""
import argparse, datetime, re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from docgen_common import ARG_GROUPS, CPU_NAME, ORDER, REPO, WHY, load_lltune
from docwriter import Confluence, Markdown

lltune = load_lltune()

GRUB_PATH = "/etc/default/grub.d/99-lowlatency.cfg"
SYSTEMD_DIR = "/etc/systemd/system"

# The three units that are handed the housekeeping set and nothing else. They are
# rendered identically, so the tables collapse them into one column rather than
# repeating the same CPU list three times.
HK_ONLY = ("user.slice", "machine.slice", "init.scope")

SLICE_ROLE = {
    "system.slice": ("housekeeping", "no",
                     "Ordinary services. Confined to housekeeping, so a stray agent cannot "
                     "land on the application's shared pool."),
    "user.slice": ("housekeeping", "no", "Login sessions. Kept off the shared pool so an "
                                         "ssh session cannot land on an application core."),
    "machine.slice": ("housekeeping", "no", "Containers and VMs, for the same reason."),
    "init.scope": ("housekeeping", "no", "PID 1 itself."),
    "irqnet.slice": ("irqnet", "no", "NIC and NVMe interrupt handling, softirq, irqbalance."),
    "pulsar.slice": ("exclusive_cores", "yes",
                     "The latency path. This cpuset exists because `isolcpus` is a real "
                     "kernel guarantee worth gating access to."),
}


def unit_path(name):
    """Render key -> the path install.sh writes."""
    if name.endswith("/10-lowlatency.conf"):
        return f"{SYSTEMD_DIR}/{name}"
    return f"{SYSTEMD_DIR}/{name}"


def unit_label(name):
    """Render key -> the unit it modifies."""
    return name.split(".d/")[0]


def plans():
    policy = lltune.load_policy()
    for name in ORDER:
        prof = lltune.load_profile(name)
        plan = lltune.build_plan(lltune.topology_from_profile(prof), policy, name)
        yield name, prof, plan


def cpus_in(spec):
    return len(lltune.expand(spec))


def arg_key(a):
    return a.split("=")[0]


def split_invariant(all_cmdlines):
    """Args identical on all shapes vs args that differ (or are absent on some)."""
    common = set(all_cmdlines[0])
    for c in all_cmdlines[1:]:
        common &= set(c)
    seen, varying = set(), []
    for c in all_cmdlines:
        for a in c:
            if a not in common and arg_key(a) not in seen:
                seen.add(arg_key(a))
                varying.append(arg_key(a))
    invariant = [a for a in all_cmdlines[0] if a in common]
    return invariant, varying


def topo_line(prof, plan):
    t = plan["topology"]
    return (f"{prof['metal_sku']} · {CPU_NAME.get(prof['name'], '')} · "
            f"{t['sockets']} socket{'s' if t['sockets'] > 1 else ''} × "
            f"{t['total_cores'] // t['sockets']} cores · "
            f"{t['numa_nodes']} NUMA node{'s' if t['numa_nodes'] > 1 else ''} "
            f"({prof.get('numa_mode', '').split(' - ')[0]}) · "
            f"L3 domain {t['cores_per_l3']} cores · SMT "
            f"{'2 → disabled at boot' if t['threads_per_core'] > 1 else 'already off (AWS)'}")


def build(doc):
    rows = list(plans())
    cmdlines = [p["cmdline"].split() for _, _, p in rows]
    invariant, varying = split_invariant(cmdlines)
    today = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    m = doc.mono

    doc.h(1, "Configuration reference - boot isolation and cgroup slices")
    doc.panel("info",
              f"Generated by scripts/build-config-reference.py on {today}. Do not hand-edit: "
              f"every list below is rendered from the planner, so it is byte-for-byte what "
              f"scripts/install.sh writes to disk for that shape. Regenerate after any change "
              f"to profiles/policy.json or a profile.")
    doc.para("This document covers the two layers that need a file on disk:")
    doc.table(["Layer", "File", "When it takes effect"],
              [["1 - boot isolation", m(GRUB_PATH), "at boot; requires a reboot"],
               ["2 - cgroup v2 slices", m(SYSTEMD_DIR + "/"),
                "systemctl daemon-reload; immediate"]])
    doc.para(
        "Layers 3 (runtime IRQ and queue pinning) and 4 (the application's core contract) are "
        "not files you edit - see ARCHITECTURES, or run "
        + m("lltune layers --profile <name>") + ".")
    doc.para(
        "The two layers are not independent. " + m("pulsar.slice") + "'s " + m("AllowedCPUs")
        + " IS the " + m("isolcpus") + " set, and both are rendered from the same plan.json "
        "field. A cgroup that let a thread onto a core the kernel had not isolated, or "
        "isolated a core no cgroup could reach, is the exact class of bug this repo is built "
        "to make impossible.")
    doc.toc()

    # ---------------------------------------------------------------- summary
    doc.h(2, "Summary: the isolation set for every shape")
    doc.para(
        m("isolcpus") + " carries the exclusive cores; " + m("irqaffinity") + " carries what "
        "is left after them, minus the shared pool - housekeeping plus irqnet. Housekeeping "
        "and IRQ cores are reserved per NUMA node, which is why node count, not core count, "
        "drives the platform's overhead.")
    doc.table(
        ["Profile", "Metal SKU", "NUMA", "Cores", "isolcpus (exclusive)", "#",
         "irqaffinity (housekeeping + irqnet)", "#"],
        [[m(name), m(prof["metal_sku"]), plan["topology"]["numa_nodes"],
          plan["topology"]["total_cores"], m(plan["isolated_cpus"]),
          plan["roles"]["exclusive"]["cpu_count"], m(plan["irq_landing_cpus"]),
          cpus_in(plan["irq_landing_cpus"])]
         for name, prof, plan in rows])

    # ---------------------------------------------------------------- part 1
    doc.h(2, "Part 1 - Boot isolation (GRUB)")
    doc.para(
        m("scripts/install.sh") + " writes " + m(GRUB_PATH) + " and re-runs update-grub or "
        "grub2-mkconfig. On AL2023 and RHEL, which have no grub.d, it patches "
        "/etc/default/grub in place after taking a timestamped backup, replacing any previous "
        "lltune block rather than appending a second one.")

    doc.h(3, "1.1 Arguments identical on every shape")
    doc.para("These carry no CPU list, so they are the same string on all seven profiles.")
    for group, args in ARG_GROUPS:
        mine = [a for a in invariant if arg_key(a) in {k for k, _ in args}]
        if not mine:
            continue
        doc.para(group)
        doc.table(["Argument", "Why"], [[m(a), WHY.get(arg_key(a), "")] for a in mine])

    doc.h(3, "1.2 Arguments that vary by shape")
    # An arg present on every shape but with a different value carries a CPU list; one
    # absent from some shapes is conditional on the silicon.
    present = {k: sum(1 for c in cmdlines if any(arg_key(a) == k for a in c)) for k in varying}
    listy = [k for k in varying if present[k] == len(cmdlines)]
    cond = [k for k in varying if present[k] < len(cmdlines)]
    doc.para(
        f"{len(listy)} arguments carry a CPU list ({', '.join(m(k) for k in listy)}) and "
        f"{len(cond)} {'are' if len(cond) != 1 else 'is'} conditional on the silicon "
        f"({', '.join(m(k) for k in cond)}). Everything in 1.1 is constant. This is the whole "
        f"of what changes between shapes at the boot layer.")
    for key in varying:
        doc.para(m(key) + " - " + WHY.get(key, ""))
        vals = []
        for (name, _, plan), cmd in zip(rows, cmdlines):
            mine = [a for a in cmd if arg_key(a) == key]
            if mine:
                vals.append([m(name), m(mine[0])])
            else:
                why = ("SMT already off on this AMD shape" if key == "nosmt"
                       else "AMD shape - intel_idle is not the idle driver"
                       if key.startswith("intel_idle") else "not applicable")
                vals.append([m(name), f"not set - {why}"])
        doc.table(["Profile", "Value"], vals)

    doc.h(3, "1.3 The installed file, per shape")
    doc.para(f"Verbatim contents of {m(GRUB_PATH)}. The cmdline is one line; it is shown "
             f"wrapped by your viewer, not by the file.")
    for name, prof, plan in rows:
        doc.h(4, name)
        doc.para(topo_line(prof, plan))
        doc.code(lltune.render_grub(plan), language="bash")
        doc.expand("Same cmdline, one argument per line",
                   doc.raw_code("\n".join(plan["cmdline"].split())))

    # ---------------------------------------------------------------- part 2
    doc.h(2, "Part 2 - cgroup v2 slices")
    keys = list(lltune.render_slices(rows[0][2]))
    dropins = [k for k in keys if ".d/" in k]
    doc.para(
        f"{len(keys)} unit files: {len(keys) - len(dropins)} new slices "
        f"({', '.join(m(k) for k in keys if '.d/' not in k)}), and {len(dropins)} drop-ins "
        f"that narrow units systemd already ships "
        f"({', '.join(m(unit_label(k)) for k in dropins)}). Drop-ins are used rather than "
        f"full replacements so a distribution update to the underlying unit is not lost.")
    doc.para(
        "cgroup v2 is required - " + m("AllowedCPUs") + " is a v2-only property, which is why "
        + m("systemd.unified_cgroup_hierarchy=1") + " and " + m("cgroup_no_v1=all")
        + " are on the cmdline in Part 1.")

    doc.h(3, "2.1 The slice map")
    doc.table(["Unit", "Holds", "Isolated", "What runs there"],
              [[m(unit), holds, iso, what.replace("`", "")]
               for unit, (holds, iso, what) in SLICE_ROLE.items()]
              + [["(none)", "shared_cores", "no",
                  "The application's non-latency pool: GC, JIT, admin endpoints, compaction. "
                  "Named by no cpuset - see below."]])
    doc.para(
        "The managed cpusets - " + m("system.slice") + ", " + m("irqnet.slice") + ", "
        + m("pulsar.slice") + " - are disjoint and cover every core on the box EXCEPT the "
        "shared pool, which is deliberately named by no slice at all.")
    doc.para(
        "A cpuset is a restriction, and it earns its place only where it gates a guarantee the "
        "kernel is actually making. " + m("isolcpus") + " is such a guarantee, so "
        + m("pulsar.slice") + " gates it. The shared cores carry no guarantee to gate, so they "
        "are left ungated and the application pins its own threads onto them.")
    doc.panel("note",
              "Because system.slice is now housekeeping-only, a unit that needs the shared "
              "pool must not run under it - the default slice for a service confines it to "
              "housekeeping. Give such a unit a slice of its own that lltune does not manage: "
              "it then keeps init's inherited affinity mask, which is every core except the "
              "isolated ones, and pins itself from there. The latency path still reaches the "
              "isolated cores only by naming Slice=pulsar.slice.",
              "Where shared work runs")
    doc.para(
        m("scripts/selftest.py") + " asserts both halves for every profile: the managed "
        "cpusets partition everything but the shared pool, and no unit's " + m("AllowedCPUs")
        + " names a shared core. " + m("user.slice") + ", " + m("machine.slice") + " and "
        + m("init.scope") + " are subsets of the housekeeping set, not extra partitions.")

    doc.h(3, "2.2 AllowedCPUs for every shape")
    doc.para(", ".join(m(u) for u in HK_ONLY) + " are rendered identically - all three get "
             "the housekeeping set - so they share one column.")
    slice_rows = []
    for name, _, plan in rows:
        sl = lltune.render_slices(plan)
        def allowed(key, sl=sl):
            return re.search(r"AllowedCPUs=(\S+)", sl[key]).group(1)
        slice_rows.append([m(name), m(allowed("system.slice.d/10-lowlatency.conf")),
                           m(allowed("user.slice.d/10-lowlatency.conf")),
                           m(allowed("irqnet.slice")), m(allowed("pulsar.slice")),
                           m(plan["roles"]["shared"]["cpus"])])
    doc.table(["Profile", "system.slice", "user / machine / init", "irqnet.slice",
               "pulsar.slice", "shared (no cpuset)"], slice_rows)

    count_rows = []
    for name, _, plan in rows:
        sl = lltune.render_slices(plan)
        n = {k: cpus_in(re.search(r"AllowedCPUs=(\S+)", v).group(1)) for k, v in sl.items()}
        count_rows.append([m(name), n["system.slice.d/10-lowlatency.conf"],
                           n["user.slice.d/10-lowlatency.conf"], n["irqnet.slice"],
                           n["pulsar.slice"], plan["roles"]["shared"]["cpu_count"],
                           plan["topology"]["total_cores"]])
    doc.table(["Profile", "system.slice", "housekeeping-only", "irqnet.slice", "pulsar.slice",
               "shared (no cpuset)", "total"], count_rows)
    doc.para(
        "Counts are CPUs. system.slice + irqnet.slice + pulsar.slice + shared sums to the "
        "total; housekeeping-only is a subset of system.slice, not an addition to it. The "
        "shared column appears in no AllowedCPUs anywhere - it is the pool the application "
        "reaches through its own inherited affinity mask.")

    doc.h(3, "2.3 The installed unit files, per shape")
    doc.para("Verbatim contents, at the path scripts/install.sh writes them to.")
    for name, prof, plan in rows:
        doc.h(4, name)
        doc.para(topo_line(prof, plan))
        for key, body in lltune.render_slices(plan).items():
            doc.para(m(unit_path(key)))
            doc.code(body, language="ini")

    # ---------------------------------------------------------------- part 3
    doc.h(2, "Part 3 - Invariants that tie the two layers together")
    doc.para("Checked at generation time across all seven profiles, and again on the host by "
             + m("lltune validate") + " (which reads /proc/cmdline and the live cpusets, not "
             "this document).")
    checks = [
        ("pulsar.slice AllowedCPUs == the isolcpus list on the cmdline",
         lambda p, s: allowed_of(s, "pulsar.slice") == p["isolated_cpus"]
                      == arg_val(p, "isolcpus").split("domain,", 1)[1]),
        ("isolcpus == nohz_full == rcu_nocbs",
         lambda p, s: arg_val(p, "nohz_full") == p["isolated_cpus"]
                      and arg_val(p, "rcu_nocbs") == p["isolated_cpus"]),
        ("irqaffinity shares no CPU with isolcpus",
         lambda p, s: not (set(lltune.expand(arg_val(p, "irqaffinity")))
                           & set(lltune.expand(p["isolated_cpus"])))),
        ("cpu0 is housekeeping, never isolated",
         lambda p, s: 0 in lltune.expand(p["roles"]["housekeeping"]["cpus"])),
        ("the managed cpusets partition every core except the shared pool",
         lambda p, s: partition_ok(p, s)),
        ("no unit's AllowedCPUs names a shared core",
         lambda p, s: not any(set(lltune.expand(re.search(r"AllowedCPUs=(\S+)", v).group(1)))
                              & set(lltune.expand(p["roles"]["shared"]["cpus"]))
                              for v in s.values())),
        ("the NIC-local node is tier 0 of the ranking",
         lambda p, s: p["nic_locality"]["tiers"][0]["nodes"]
                      == [p["nic_locality"]["nic_numa_node"]]),
        ("housekeeping-only units are a subset of system.slice",
         lambda p, s: set(lltune.expand(allowed_of(s, "user.slice.d/10-lowlatency.conf")))
                      <= set(lltune.expand(allowed_of(s, "system.slice.d/10-lowlatency.conf")))),
        ("every slice gets every NUMA node in AllowedMemoryNodes",
         lambda p, s: all(re.search(r"AllowedMemoryNodes=(\S+)", v).group(1) == p["memory_nodes"]
                          for v in s.values())),
    ]
    failures, inv_rows = [], []
    for label, fn in checks:
        ok = []
        for name, _, plan in rows:
            sl = lltune.render_slices(plan)
            if fn(plan, sl):
                ok.append(name)
            else:
                failures.append((label, name))
        inv_rows.append([label, "all 7 shapes" if len(ok) == len(rows)
                         else ", ".join(ok) or "NONE"])
    doc.table(["Invariant", "Holds for"], inv_rows)
    if failures:
        for label, name in failures:
            print(f"INVARIANT FAILED: {label} on {name}", file=sys.stderr)
        sys.exit(f"{len(failures)} invariant failure(s); refusing to write a document that "
                 f"documents a broken plan")
    doc.para("Regenerate: ./scripts/build-config-reference.py - terminal equivalent: "
             "./bin/lltune layers --profile <name> - live host: "
             "./bin/lltune render --live -o out/")
    return doc.text()


def allowed_of(slices, key):
    return re.search(r"AllowedCPUs=(\S+)", slices[key]).group(1)


def arg_val(plan, key):
    for a in plan["cmdline"].split():
        if a.split("=")[0] == key:
            return a.split("=", 1)[1]
    return None


def partition_ok(plan, slices):
    """Disjoint, and covering everything the shared pool does not."""
    parts = []
    for key in ("system.slice.d/10-lowlatency.conf", "irqnet.slice", "pulsar.slice"):
        parts.append(set(lltune.expand(allowed_of(slices, key))))
    union = set().union(*parts)
    disjoint = all(not (a & b) for i, a in enumerate(parts) for b in parts[i + 1:])
    everything = (set(lltune.expand(plan["non_isolated_cpus"]))
                  | set(lltune.expand(plan["isolated_cpus"])))
    return disjoint and union == everything - set(lltune.expand(plan["roles"]["shared"]["cpus"]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--md", default=str(REPO / "docs" / "CONFIG-REFERENCE.md"))
    ap.add_argument("--confluence",
                    default=str(REPO / "docs" / "confluence" / "CONFIG-REFERENCE.confluence"))
    args = ap.parse_args()
    for path, cls in ((args.md, Markdown), (args.confluence, Confluence)):
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        text = build(cls())
        out.write_text(text)
        print(f"wrote {out}  ({len(text.splitlines())} lines, 7 profiles)")


if __name__ == "__main__":
    main()
